### ISSUE TITLE
prawcore.exceptions.TooLarge: received 413 HTTP response

### ISSUE THREAD

**Issue by dankstarr** [asad70/reddit-sentiment-analysis#1]
I have been trying to grind at this error for the past week now. I have tried using the same parameters as in the example and it still gives the same error.
I also tried using https://pypi.org/project/pmaw/ for multi-threading it, but got the same error.

line 75, in <module>
submission.comments.replace_more(limit=limit)
prawcore.exceptions.TooLarge: received 413 HTTP response

**Comment by asad70** [comment]
Hey, it happens when the program is going thru posts with large number of comments >50k comments.
Here's a link to the error for more info: https://github.com/praw-dev/praw/issues/1401
But adding the code into try/except block should does the work. I have added try/except to original code.

**Comment by dankstarr** [comment]
Hey, really appreciate the prompt reply. I had tried adding another try/except continue clause but it was skipping through the rest of the posts. Your new commit fixed it. 
I am trying to get this code deployed to a heroku web server through flask. Is that okay with you?

**Comment by asad70** [comment]
Yes, you are free to use this code however you want. 

If you are willing to make it public i would love to see the finished version of it.

**Comment by AnniaLevko** [comment]
Hi, Im having the same problem with +50k comments, is there a solution yet? Cant find it anywhere

**Comment by asad70** [comment]
> Hi, Im having the same problem with +50k comments, is there a solution yet? Cant find it anywhere

@AnniaLevko Hey, it seems like a limitation on reddit side.

Here's more info and workaround: https://www.reddit.com/r/redditdev/comments/7si641/praw_530_toolarge_received_413_http_response_when/
